#!/bin/bash
RUNS=1
PROGRAM=sander
HOMEDIR=$1
RESIDUE=$2

sed s/XXX/$RESIDUE/g ${HOMEDIR}SimFiles/Mutation/Production_bellymask_template.in > ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in

for i in $RUNS
do
 mkdir Run_$i
 cd Run_$i
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_0_100.out -c ../Store/Solv_0_100.inpcrd -p ../Store/Solv_0_100.prmtop -r 0_100.restart -x 0_100.mdcrd
 fail=0
 until grep -q "wallclock" Production_0_100.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_0_100.out -c ../Store/Solv_0_100.inpcrd -p ../Store/Solv_0_100.prmtop -r 0_100.restart -x 0_100.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_10_90.out -c 0_100.restart -p ../Store/Solv_10_90.prmtop -r 10_90.restart -x 10_90.mdcrd
 fail=0
 until grep -q "wallclock" Production_10_90.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_0_100.out -c ../Store/Solv_0_100.inpcrd -p ../Store/Solv_0_100.prmtop -r 0_100.restart -x 0_100.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_10_90.out -c 0_100.restart -p ../Store/Solv_10_90.prmtop -r 10_90.restart -x 10_90.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_20_80.out -c 10_90.restart -p ../Store/Solv_20_80.prmtop -r 20_80.restart -x 20_80.mdcrd
 fail=0
 until grep -q "wallclock" Production_20_80.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_10_90.out -c 0_100.restart -p ../Store/Solv_10_90.prmtop -r 10_90.restart -x 10_90.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_20_80.out -c 10_90.restart -p ../Store/Solv_20_80.prmtop -r 20_80.restart -x 20_80.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_30_70.out -c 20_80.restart -p ../Store/Solv_30_70.prmtop -r 30_70.restart -x 30_70.mdcrd
 fail=0
 until grep -q "wallclock" Production_30_70.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_20_80.out -c 10_90.restart -p ../Store/Solv_20_80.prmtop -r 20_80.restart -x 20_80.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_30_70.out -c 20_80.restart -p ../Store/Solv_30_70.prmtop -r 30_70.restart -x 30_70.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_40_60.out -c 30_70.restart -p ../Store/Solv_40_60.prmtop -r 40_60.restart -x 40_60.mdcrd
 fail=0
 until grep -q "wallclock" Production_40_60.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_30_70.out -c 20_80.restart -p ../Store/Solv_30_70.prmtop -r 30_70.restart -x 30_70.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_40_60.out -c 30_70.restart -p ../Store/Solv_40_60.prmtop -r 40_60.restart -x 40_60.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_50_50.out -c 40_60.restart -p ../Store/Solv_50_50.prmtop -r 50_50.restart -x 50_50.mdcrd
 fail=0
 until grep -q "wallclock" Production_50_50.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_40_60.out -c 30_70.restart -p ../Store/Solv_40_60.prmtop -r 40_60.restart -x 40_60.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_50_50.out -c 40_60.restart -p ../Store/Solv_50_50.prmtop -r 50_50.restart -x 50_50.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_60_40.out -c 50_50.restart -p ../Store/Solv_60_40.prmtop -r 60_40.restart -x 60_40.mdcrd
 fail=0
 until grep -q "wallclock" Production_60_40.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_50_50.out -c 40_60.restart -p ../Store/Solv_50_50.prmtop -r 50_50.restart -x 50_50.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_60_40.out -c 50_50.restart -p ../Store/Solv_60_40.prmtop -r 60_40.restart -x 60_40.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_70_30.out -c 60_40.restart -p ../Store/Solv_70_30.prmtop -r 70_30.restart -x 70_30.mdcrd
 fail=0
 until grep -q "wallclock" Production_70_30.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_60_40.out -c 50_50.restart -p ../Store/Solv_60_40.prmtop -r 60_40.restart -x 60_40.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_70_30.out -c 60_40.restart -p ../Store/Solv_70_30.prmtop -r 70_30.restart -x 70_30.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_80_20.out -c 70_30.restart -p ../Store/Solv_80_20.prmtop -r 80_20.restart -x 80_20.mdcrd
 fail=0
 until grep -q "wallclock" Production_80_20.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_70_30.out -c 60_40.restart -p ../Store/Solv_70_30.prmtop -r 70_30.restart -x 70_30.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_80_20.out -c 70_30.restart -p ../Store/Solv_80_20.prmtop -r 80_20.restart -x 80_20.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_90_10.out -c 80_20.restart -p ../Store/Solv_90_10.prmtop -r 90_10.restart -x 90_10.mdcrd
 fail=0
 until grep -q "wallclock" Production_90_10.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_80_20.out -c 70_30.restart -p ../Store/Solv_80_20.prmtop -r 80_20.restart -x 80_20.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_90_10.out -c 80_20.restart -p ../Store/Solv_90_10.prmtop -r 90_10.restart -x 90_10.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_100_0.out -c 90_10.restart -p ../Store/Solv_100_0.prmtop -r 100_0.restart -x 100_0.mdcrd
 fail=0
 until grep -q "wallclock" Production_100_0.out
 do
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_90_10.out -c 80_20.restart -p ../Store/Solv_90_10.prmtop -r 90_10.restart -x 90_10.mdcrd
  nohup $PROGRAM -O -i ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in -o Production_100_0.out -c 90_10.restart -p ../Store/Solv_100_0.prmtop -r 100_0.restart -x 100_0.mdcrd
  fail=$(($fail+1))
  if [ $fail -eq 10 ]
  then
   break
  fi
 done
 cd ../
done
rm ${HOMEDIR}SimFiles/Mutation/Production_bellymask.in
